(require '[kotoba.script :as script] '[clojure.string :as str])
(require 'kotoba.script-test)
(def out-dir "test/fixtures/parity")
(def doubles [0.5 1.5 100.0 0.001 0.0009 1234567.0 12345678.0 1.0E7 1.0E21 1.5E-5 123.456 9999999.0
              3.141592653589793 1.0E300 4.9E-324 2.2250738585072014E-308 0.1 100.5 -2.5E10 1.0E-7
              -0.001 1.0E-3 0.30000000000000004 1234.5 72057594037927936.0 1.7976931348623157E308 -1.0 2.0 10.0])
(spit (str out-dir "/f64.edn") (pr-str (mapv (fn [d] [(Long/toHexString (Double/doubleToRawLongBits d)) (Double/toString d)]) doubles)))
(def report
  (->> (ns-publics 'kotoba.script-test)
       (keep (fn [[sym v]]
               (let [val (try @v (catch Throwable _ nil))]
                 (when (and (map? val) (contains? #{:kotoba.kir/v3 :kotoba.kir/v4} (:format val)))
                   (let [r (try {:source (script/emit val)} (catch Exception e {:error (ex-message e)}))]
                     (when (:source r)
                       (spit (str out-dir "/" (name sym) ".kir.edn") (pr-str val))
                       (spit (str out-dir "/" (name sym) ".mjs") (:source r)))
                     [(name sym) (if (:source r) :ok (:error r))])))))
       (sort-by first) vec))
(spit (str out-dir "/README.md")
      (str "Golden pairs generated by the JVM emitter (`scripts/gen-parity-golden.clj`) for the nbb parity test\n"
           "(`test/nbb/parity.cljs`). `<name>.kir.edn` is the KIR fixture exported by the JVM test namespace,\n"
           "`<name>.mjs` the module the JVM emitted for it; `f64.edn` pairs raw f64 bits with `Double.toString`.\n"
           "Regenerate after any emitter change: `clojure -M:golden`.\n"))
(println (pr-str report))
