(require '[kotoba.script :as script] '[kotoba.lang.text :as str] '[clojure.walk :as walk])
(require 'kotoba.script-test)
(def out-dir "test/fixtures/parity")
(def doubles [0.5 1.5 100.0 0.001 0.0009 1234567.0 12345678.0 1.0E7 1.0E21 1.5E-5 123.456 9999999.0
              3.141592653589793 1.0E300 4.9E-324 2.2250738585072014E-308 0.1 100.5 -2.5E10 1.0E-7
              -0.001 1.0E-3 0.30000000000000004 1234.5 72057594037927936.0 1.7976931348623157E308 -1.0 2.0 10.0])
(spit (str out-dir "/f64.edn") (pr-str (mapv (fn [d] [(Long/toHexString (Double/doubleToRawLongBits d)) (Double/toString d)]) doubles)))

(defn whole-double?
  "A finite (or infinite) double with no fractional part -- `-0.0`, `2.0`,
  `##Inf`. Printed as a plain EDN number the cljs reader hands these back as
  an integer (`-0.0` even reads as `0`), so the golden carries them as raw
  bits under the `kotoba.parity/f64-bits` tag; `test/nbb/parity.cljs`
  registers the reader. NaN and fractional doubles print as themselves."
  [x]
  (and (instance? Double x) (not (Double/isNaN x)) (== x (Math/rint x))))

(defn tag-doubles [kir]
  (walk/postwalk (fn [x] (if (whole-double? x)
                           (tagged-literal 'kotoba.parity/f64-bits
                                           (Long/toHexString (Double/doubleToRawLongBits x)))
                           x))
                 kir))

;; Clear stale goldens so a renamed/removed fixture does not linger.
(doseq [f (.listFiles (java.io.File. out-dir))
        :when (re-find #"\.(kir|opts)\.edn$|\.mjs$" (.getName f))]
  (.delete f))

(def report
  (->> (ns-publics 'kotoba.script-test)
       (keep (fn [[sym v]]
               (let [val (try @v (catch Throwable _ nil))
                     opts (:emit-opts (meta v))]
                 (when (and (map? val) (contains? #{:kotoba.kir/v3 :kotoba.kir/v4} (:format val)))
                   (let [r (try {:source (if opts (script/emit val opts) (script/emit val))}
                                (catch Exception e {:error (ex-message e)}))]
                     (if (:source r)
                       (do (spit (str out-dir "/" (name sym) ".kir.edn") (pr-str (tag-doubles val)))
                           (when opts (spit (str out-dir "/" (name sym) ".opts.edn") (pr-str opts)))
                           (spit (str out-dir "/" (name sym) ".mjs") (:source r)))
                       (println "SKIP" (name sym) "-- emit threw:" (:error r)))
                     [(name sym) (if (:source r) (count (:source r)) (:error r))])))))
       (sort-by first) vec))
(def ok (filter (comp number? second) report))
(spit (str out-dir "/README.md")
      (str "Golden pairs generated by the JVM emitter (`scripts/gen-parity-golden.clj`) for the nbb parity test\n"
           "(`test/nbb/parity.cljs`). `<name>.kir.edn` is a KIR fixture exported by the JVM test namespace\n"
           "(every public var of `kotoba.script-test` whose value is a KIR map), `<name>.mjs` the module the\n"
           "JVM emitted for it, `<name>.opts.edn` (when present) the emit options taken from the var's\n"
           "`^{:emit-opts …}` metadata; `f64.edn` pairs raw f64 bits with `Double.toString`.\n"
           "Whole-number doubles inside a fixture (`-0.0`, `##Inf`) are written as\n"
           "`#kotoba.parity/f64-bits \"<hex>\"` because the cljs EDN reader would read them as integers.\n"
           "Regenerate after any emitter change: `clojure -M:golden`.\n\n"
           "Last generation: " (count ok) " KIR goldens, " (reduce + (map second ok)) " bytes of emitted ESM.\n"))
(println (pr-str report))
(println "GOLDENS" (count ok) "BYTES" (reduce + (map second ok)))
